# Site settings
title: comalex
email: stupak.alexn@gmail.com
description: > # this means to ignore newlines until "baseurl:"My personal website"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  comalex

# Build settings
markdown: kramdown
